apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minato-ui.fullname" . }}-app-secrets
  labels:
    {{- include "minato-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ randAlphaNum 64 }}
  {{- if .Values.app.auth.oidc.enabled }}
  AUTH_OIDC_CLIENT_SECRET: {{ .Values.app.auth.oidc.clientSecret | quote }}
  {{- end }}
