/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 OK if the control plane is running
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Control plane is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 OK if the control plane is ready to serve requests
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Control plane is ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth configuration discovery
         * @description Returns the available authentication modes and configuration.
         *     This endpoint is public and used by the UI to auto-configure auth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Auth configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List game servers
         * @description List all GameServers across all namespaces
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of game servers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameServer"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers/{namespace}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create game server
         * @description Create a new GameServer in the specified namespace (admin only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GameServer"];
                };
            };
            responses: {
                /** @description Game server created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameServer"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game server
         * @description Get a specific GameServer by namespace and name
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game server details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameServer"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete game server
         * @description Delete a GameServer (admin only)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game server deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers/{namespace}/{name}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available actions
         * @description List actions available for a game server based on its profile
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available actions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Action"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers/{namespace}/{name}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute action
         * @description Execute an action on a game server (operator+ only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                    action: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            responses: {
                /** @description Action execution started */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Execution ID */
                            name?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers/{namespace}/{name}/actions/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get action execution status
         * @description Get the status of an action execution
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                    executionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action execution details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionExecution"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameservers/{namespace}/{name}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List snapshots
         * @description List snapshots for a game server
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of snapshots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameSnapshot"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create snapshot
         * @description Create a snapshot for a game server (operator+ only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameSnapshot"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameserverfleets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List fleets
         * @description List all GameServerFleets across all namespaces
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of fleets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameServerFleet"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gameserverfleets/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get fleet
         * @description Get a specific GameServerFleet
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fleet details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameServerFleet"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List profiles
         * @description List all GameProfiles (cluster-scoped)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of game profiles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameProfile"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile
         * @description Get a specific GameProfile
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameProfile"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apikeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description List all API keys without secret values (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of API keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIKey"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create API key
         * @description Generate a new API key (admin only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Key name */
                        name?: string;
                        /**
                         * @description Role for the key
                         * @enum {string}
                         */
                        role?: "viewer" | "operator" | "admin";
                    };
                };
            };
            responses: {
                /** @description API key created (key value shown once) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name?: string;
                            role?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** @description The API key value (shown once) */
                            key?: string;
                            warning?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apikeys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke API key
         * @description Delete/revoke an API key (admin only)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    keyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API key revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "authModes": [
         *         "basic",
         *         "oidc",
         *         "apikey"
         *       ],
         *       "oidcIssuer": "https://auth.7kgroup.com/realms/minato",
         *       "basicEnabled": true
         *     }
         */
        AuthConfig: {
            /** @description Available authentication modes */
            authModes: ("none" | "basic" | "oidc" | "apikey")[];
            /**
             * Format: uri
             * @description OIDC issuer URL (if OIDC is enabled)
             */
            oidcIssuer?: string | null;
            /** @description Whether Basic auth is enabled */
            basicEnabled: boolean;
        };
        GameServer: {
            /** @example operator.minato.io/v1 */
            apiVersion?: string;
            /** @example GameServer */
            kind?: string;
            metadata?: {
                name?: string;
                namespace?: string;
                /** Format: date-time */
                creationTimestamp?: string;
            };
            spec?: components["schemas"]["GameServerSpec"];
            status?: components["schemas"]["GameServerStatus"];
        };
        GameServerSpec: {
            /** @description Reference to GameProfile name */
            profile?: string;
            /** @description Environment variables */
            env?: {
                [key: string]: string;
            };
            storage?: components["schemas"]["StorageSpec"];
            priorityClassName?: string;
            lifecycle?: {
                idleTimeoutSeconds?: number;
            };
        };
        GameServerStatus: {
            /** @enum {string} */
            state?: "Provisioning" | "Running" | "Idle" | "Stopped" | "Error";
            /** @description Current player count */
            players?: number;
            /** @description Maximum player capacity */
            playerCapacity?: number;
            agentVersion?: string;
            endpoints?: components["schemas"]["Endpoint"][];
            conditions?: Record<string, never>[];
        };
        Endpoint: {
            name?: string;
            address?: string;
            port?: number;
        };
        StorageSpec: {
            /** @example 20Gi */
            size?: string;
            storageClass?: string;
            snapshotRef?: {
                name?: string;
                namespace?: string;
            };
        };
        Action: {
            name?: string;
            description?: string;
            /**
             * @default allow
             * @enum {string}
             */
            concurrency: "serialize" | "exclusive" | "allow";
            /** @example 5m */
            timeout?: string;
            params?: {
                [key: string]: components["schemas"]["ActionParam"];
            };
        };
        ActionParam: {
            /** @enum {string} */
            type?: "string" | "number" | "boolean";
            required?: boolean;
            default?: string;
        };
        ActionExecution: {
            apiVersion?: string;
            /** @example ActionExecution */
            kind?: string;
            metadata?: {
                name?: string;
                namespace?: string;
                /** Format: date-time */
                creationTimestamp?: string;
            };
            spec?: {
                targetRef?: {
                    apiVersion?: string;
                    kind?: string;
                    name?: string;
                    namespace?: string;
                };
                actionName?: string;
                params?: {
                    [key: string]: string;
                };
                caller?: string;
            };
            status?: {
                /** @enum {string} */
                state?: "Pending" | "Running" | "Succeeded" | "Failed" | "Rejected";
                /** Format: date-time */
                startedAt?: string;
                /** Format: date-time */
                completedAt?: string;
                result?: string;
                error?: string;
            };
        };
        GameSnapshot: {
            apiVersion?: string;
            /** @example GameSnapshot */
            kind?: string;
            metadata?: {
                name?: string;
                namespace?: string;
                /** Format: date-time */
                creationTimestamp?: string;
            };
            spec?: {
                gameServerRef?: string;
                /** @description Cron expression for scheduled snapshots */
                schedule?: string;
                retention?: {
                    count?: number;
                    /** @example 720h */
                    duration?: string;
                };
            };
            status?: {
                /** @enum {string} */
                state?: "Pending" | "Ready" | "Failed";
                /** Format: date-time */
                readyAt?: string;
                size?: string;
            };
        };
        GameServerFleet: {
            apiVersion?: string;
            /** @example GameServerFleet */
            kind?: string;
            metadata?: {
                name?: string;
                namespace?: string;
                /** Format: date-time */
                creationTimestamp?: string;
            };
            spec?: {
                profile?: string;
                replicas?: number;
                template?: {
                    spec?: components["schemas"]["GameServerSpec"];
                };
                updateStrategy?: {
                    /** @enum {string} */
                    type?: "RollingUpdate" | "Recreate";
                    rollingUpdate?: {
                        maxUnavailable?: number;
                    };
                };
                priorityClassName?: string;
                topologySpreadConstraints?: Record<string, never>[];
            };
            status?: {
                replicas?: number;
                readyReplicas?: number;
                updatedReplicas?: number;
                availableReplicas?: number;
                conditions?: Record<string, never>[];
            };
        };
        GameProfile: {
            apiVersion?: string;
            /** @example GameProfile */
            kind?: string;
            metadata?: {
                name?: string;
            };
            spec?: components["schemas"]["GameProfileSpec"];
        };
        GameProfileSpec: {
            displayName?: string;
            /** @description Game server container image */
            image?: string;
            ports?: components["schemas"]["Port"][];
            environment?: components["schemas"]["EnvVar"][];
            resources?: {
                requests?: {
                    cpu?: string;
                    memory?: string;
                };
                limits?: {
                    cpu?: string;
                    memory?: string;
                };
            };
            storage?: {
                mountPath: string;
                sizeDefault?: string;
            };
            agent?: {
                image?: string;
                version?: string;
            };
            actions?: components["schemas"]["Action"][];
            capabilities?: {
                files?: boolean;
                sftp?: boolean;
                backup?: boolean;
                restoreFromSnapshot?: boolean;
            };
        };
        Port: {
            name?: string;
            containerPort?: number;
            /**
             * @default TCP
             * @enum {string}
             */
            protocol: "TCP" | "UDP";
        };
        EnvVar: {
            key?: string;
            default?: string;
            required?: boolean;
        };
        APIKey: {
            name?: string;
            /** @enum {string} */
            role?: "viewer" | "operator" | "admin";
            /** Format: date-time */
            createdAt?: string;
            createdBy?: string;
        };
        Error: {
            error?: string;
            message?: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
